### ISSUE TITLE
supernode 本地无法运行

### ISSUE THREAD

**Issue by meglory** [alibaba/Dragonfly#11]
RT，我在本地运行supernode，报了如下错误：

十一月 29, 2017 5:21:28 下午 org.apache.coyote.AbstractProtocol init
信息: Initializing ProtocolHandler ["http-bio-8080"]
十一月 29, 2017 5:21:28 下午 org.apache.catalina.core.StandardService startInternal
信息: Starting service Tomcat
十一月 29, 2017 5:21:28 下午 org.apache.catalina.core.StandardEngine startInternal
信息: Starting Servlet Engine: Apache Tomcat/7.0.37
十一月 29, 2017 5:21:32 下午 org.apache.catalina.core.ApplicationContext log
信息: No Spring WebApplicationInitializer types detected on classpath
十一月 29, 2017 5:21:32 下午 org.apache.catalina.core.ApplicationContext log
信息: Initializing Spring root WebApplicationContext
十一月 29, 2017 5:21:32 下午 org.springframework.web.context.ContextLoader initWebApplicationContext
信息: Root WebApplicationContext: initialization started
十一月 29, 2017 5:21:33 下午 org.springframework.web.context.support.XmlWebApplicationContext prepareRefresh
信息: Refreshing Root WebApplicationContext: startup date [Wed Nov 29 17:21:33 CST 2017]; root of context hierarchy
十一月 29, 2017 5:21:33 下午 org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
信息: Loading XML bean definitions from class path resource [application-context.xml]
十一月 29, 2017 5:21:34 下午 org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor <init>
信息: JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
十一月 29, 2017 5:21:35 下午 org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler initialize
信息: Initializing ExecutorService  'scheduler'
十一月 29, 2017 5:21:35 下午 org.springframework.web.context.support.XmlWebApplicationContext postProcessAfterInitialization
信息: **_Bean 'scheduler' of type [class org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)_**
十一月 29, 2017 5:21:35 下午 org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
信息: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@39641cb4: defining beans [scheduler,org.springframework.context.annotation.internalAsyncAnnotationProcessor,org.springframework.context.annotation.internalScheduledAnnotationProcessor,monitorService,netConfigNotification,powerRateLimiter,peerRepository,peerTaskRepository,progressRepository,taskRepository,cacheDetectorImpl,linkPositiveGc,cdnManagerImpl,cdnReporter,commonPeerDispatcher,fileMetaDataService,peerRegistryService,peerService,peerTaskService,progressService,taskService,lockService,dataGcService,diskSpaceGcTimer,downSpaceCleaner,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,utilBeanPool,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor,org.springframework.scheduling.annotation.SchedulingConfiguration]; root of factory hierarchy
Disconnected from the target VM, address: '127.0.0.1:52916', transport: 'socket'

Process finished with exit code 1

网上查了半天，没找到解决办法，求大神指点下这个报错如何解决。

**Comment by chenchaobing** [comment]
你本地的运行环境是什么？

如果是mac的话，尝试做一下以下操作：
修改 com.alibaba.dragonfly.supernode.common.Constants 中的CDN_HOME
修改 resources/hogback-config.properties 中的 log_home
把/home/admin目录改成本地存在的目录。

**Comment by meglory** [comment]
十分感谢，我把CDN_HOME改了之后就可以了，不过这个是不是应该有个提示呢，不然让人摸不着头脑啊，哈哈^_^
