### ISSUE TITLE
[question]客户端下载完成后，某些场景可能无法删除本地临时缓存

### ISSUE THREAD

**Issue by xq2248** [alibaba/Dragonfly#111]
客户端下载完成后，后台驻留的dfget程序，会遗留3分钟，3分钟内其他peer可以继续从这个客户端中下载，但是如果这个时候客户端掉电或者重启，本地$HOME/.smalldragonfly/data中的文件不会被删除，成为垃圾文件？

**Comment by lowzj** [comment]
如果异常终止，这些文件会在下一次dfget进程启动后删除
