### ISSUE TITLE
failed to download small files within the timeout period

### ISSUE THREAD

**Issue by nonly** [alibaba/Dragonfly#122]
## problem
**hundreds of peers download files at the same time,  but some download tasks failed;**
- failure rate is less than 1%;
- failure reasons are same:  failed to download small files(< 64KB) within the timeout period (10s);
- dfget version 0.1.0

### log
**dfget logs as follows:**
>[2018-07-30 15:09:41,837] INFO sign:27352-1532934581.689 lineno:95 : do register result:{u'code': 200, u'data': {u'pieceSize': 4194304, u'fileLength': 16222, u'taskId': u'5f726922a225525f49e6531c7944e1b66cef23abec69fc6a3d373fb5a7af9819'}} and cost 0.005
 
[2018-07-30 15:09:41,842] INFO sign:27352-1532934581.689 lineno:115 pull piece task: ... result:{u'msg': u'piece resource lack', u'code': 602} and sleep 0.671 ...
...
...
[2018-07-30 15:09:50,340] INFO sign:27352-1532934581.689 lineno:115 pull piece task: ...  result:{u'msg': u'piece resource lack', u'code': 602} and sleep 1.747 ...
download FAIL cost:10.153s length:16222 reason:0

**supernode logs as follows:**
> app.log:2018-07-30 15:09:41.213  INFO 30099 --- [Thread-40] c.a.d.s.service.impl.CdnReporterImpl     : taskId:5f726922a225525f49e6531c7944e1b66cef23abec69fc6a3d373fb5a7af9819 fileLength:16227 status:SUCCESS from:local
app.log:2018-07-30 15:09:41.213  INFO 30099 --- [Thread-40] c.a.d.supernode.service.cdn.SuperWriter  : taskId:5f726922a225525f49e6531c7944e1b66cef23abec69fc6a3d373fb5a7af9819 readCost:0,totalCost:63,fileLength:16222,realMd5:f92cb5624ba1abaef66b77e1a8f457d8

## conclusion
from logs , i assume supernode has downloaded files successfully at 2018-07-30 15:09:41.213;
but i don't know why superNode always tell peer to wait until dfget timeout(10s) is reached(2018-07-30 15:09:50,34).

**Comment by lowzj** [comment]
There is a bug of supernode 0.1.0. If your supernode's version is 0.1.0, please upgrade to `0.1.1`.

**Comment by nonly** [comment]
ok,  does [pr 93](https://github.com/alibaba/Dragonfly/pull/93) fix the bug?
