### ISSUE TITLE
[question] 如何确定镜像拉取请求经过了Dragonfly并以P2P的方式拉取了？

### ISSUE THREAD

**Issue by xiangpengzhao** [alibaba/Dragonfly#134]
在集群中部署Dragonfly之后简单测试下载普通大文件，可以看到当在一些节点上已经下载过该文件，再在别的节点去下载时，下载时间有显著的缩短。

但是配置了镜像下载相关的参数后，以同样的方法去测试下载大镜像，从时间上看，在所有节点上的下载时间均没有明显的差异，也就是说后面的下载时间并没有缩短。

请问如何确认标题中提到的问题？多谢！

环境信息：
supernode是以容器的方式启动的，按照[测试验证](https://github.com/alibaba/Dragonfly/blob/master/docs/zh/install_server.md#4-%E6%B5%8B%E8%AF%95%E9%AA%8C%E8%AF%81)所提及的方式验证结果：
```
ps aux|grep nginx      # 有一堆nginx的master和worker进程
ps aux|grep tomcat     # 无tomcat
telnet 127.0.0.1 8001  # Connected to 127.0.0.1
telent 127.0.0.1 8002  # Connected to 127.0.0.1
```

df-daemon 启动命令：
```
df-daemon --registry=https://index.docker.io/v1/
```

/etc/docker/daemon.json 文件内容：
```
{
  "registry-mirrors": ["http://127.0.0.1:65001"]
}
```

哪里有漏配置什么吗？

**Comment by lowzj** [comment]
@xiangpengzhao 在pull镜像的时候看下机器上 $HOME/.small-dragonfly/logs/dfclient.log 有无日志输出，如果有的话，那就通过了蜻蜓下载。

出错原因可以看下 `$HOME/.small-dragonfly/logs/dfdamon.log`。

你的`--registry`参数有误，目前dfdaemon是按照`://`解析此参数，后半部分`index.docker.io/v1/`会被当成域名，所以连接时会出错，导致dfdamon失效，直接从源下载了。把参数改为`https://index.docker.io`，测试是可以的。

**Comment by xiangpengzhao** [comment]
@lowzj 行家一出手，就知有没有！按您说的方式问题已经解决，并且能够以肉眼可辨的方式看到下载速度有明显的提升。非常感谢！

**Comment by anjia0532** [comment]
@aisensiy 支持
