### ISSUE TITLE
看过这个项目后的几点想法

### ISSUE THREAD

**Issue by moooofly** [alibaba/Dragonfly#15]
整个工程看下来，产生如下几点想法

- 文档中存在较多错误，并且不全；
- 关于 P2P 方面的介绍缺失；
- 感觉更像是实验性放出，而不是真正做好开源准备的产品；

我相信应该是有更多、更好的内容会放出来，但目前的情况，确实不敢恭维~

**Comment by zhouhaibing089** [comment]
一方面, 我同意这些都是事实: 文档不是很完整, 代码质量也不是很健康等等.

另外一方面, 我也觉得我们对待开源的态度应该是包容的, 从我自己的角度看, 代码也许不是最重要的, 方法才是, 从这个角度上来看, 阿里分享出他们解决问题的方法也是值得肯定的.

最后, 一个项目的能否健康快速成长, 也需要很多人的努力, 所以也许我应该问这样的问题:

 > 文档中存在较多错误，并且不全

能否更具体一点呢, 哪些地方你觉得有错误, 并且需要新增的.

@garfield009

**Comment by garfield009** [comment]
多谢提出的建议和问题，开源也是希望借助大家的力量使产品更加完善。针对代码和文档方面的不足，请给出一些具体的建议，十分感谢！

**Comment by moooofly** [comment]
@garfield009 @zhouhaibing089 
👌 ，我会抽时间整理一些我的想法出来~

**Comment by iambowen** [comment]
这个和阿里在生产环境使用的dragonfly系统有什么区别？

**Comment by talentwill** [comment]
CM 和 Host 如何组成P2P网络部分比较关心，建议可以补充点这方面的doc。

**Comment by foxwang** [comment]
CM和host如何组成P2P网络？
dfget如何与CM交互？是否需要配置？
按照文档搞了，结果dfget感觉和wget的结果没啥区别啊
