### ISSUE TITLE
dfget-go是不是还没ready的

### ISSUE THREAD

**Issue by shenlanse** [alibaba/Dragonfly#151]
dfget-go是不是还没有完成的，我看代码dfget-go很多函数都没实现，也不能下载文件。
这个有时间计划吗？

**Comment by shenlanse** [comment]
@zhouhaibing089 @allencloud  这个项目还有人在维护吗？ 请问superNode和dfget的golang implementation有计划表吗？

**Comment by lowzj** [comment]
@shenlanse 0.2.x分支是目前可用的版本，0.3.0版本这个月底会release
supernode的golang实现下个月开始
