### ISSUE TITLE
关于多个超级节点主机下载问题

### ISSUE THREAD

**Issue by dylan120** [alibaba/Dragonfly#154]
###  Issue Description
客户端下载文件时,dfget通过参数node指定多个超级节点，测试中返现下载的时候只连到其中一个超级节点，无法多个超级节点同时对一个客户端提供下载服务吗？如果是这样，假如我一个机房有两个超级节点，机房内的客户端注册到不同的超级节点，客户端之间共享文件是不是只能在注册了同一台超级节点才能实现，注册了不同超级节点的客户端之间是否就不能彼此共享文件

**Comment by lowzj** [comment]
是的，注册到同一个超级节点的客户端构成一个p2p网络

**Comment by dylan120** [comment]
> 是的，注册到同一个超级节点的客户端构成一个p2p网络

好谢谢

**Comment by dylan120** [comment]
哈喽，还有两个疑问
1、客户端如果指定多个超级节点下载，选择注册哪台超级节点是基于什么逻辑（随机or负载还是其他）？
2、已注册超级节点A在下载任务过程中挂掉，客户端自动切换到另外的超级节点B也是可以基于原先从超级节点A已下载好的文件片段断点续传吗？

**Comment by lowzj** [comment]
1. 随机。客户端在启动后会打乱超级节点列表，然后顺序访问。
2. 切换超级节点后，当前客户端进程会基于已下载的分片接着下载。

**Comment by dylan120** [comment]
好的，谢谢
