### ISSUE TITLE
docker proxy error

### ISSUE THREAD

**Issue by lifubang** [alibaba/Dragonfly#16]
when docker pull, there are some errors as follows:
root@iZ2ze7tbgo9lk7jubiy6tcZ:~# df-daemon -registry https://docker.acmcoder.com -port 18001

launch df-daemon on port:18001
2017/12/12 18:21:28 http: proxy error: context canceled
2017/12/12 18:21:32 http: proxy error: context canceled
2017/12/12 18:21:34 http: proxy error: context canceled
2017/12/12 18:21:35 http: proxy error: context canceled
2017/12/12 18:21:36 http: proxy error: context canceled
2017/12/12 18:21:36 http: proxy error: dial tcp: i/o timeout
2017/12/12 18:21:37 http: proxy error: context canceled
2017/12/12 18:21:38 http: proxy error: context canceled
Killed
root@iZ2ze7tbgo9lk7jubiy6tcZ:~# curl https://docker.acmcoder.com
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>Harbor</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico?v=2">
</head>

<body style="overflow-y: hidden;">
    <harbor-app>
        <div class="spinner spinner-lg app-loading">
            Loading...
        </div>
    </harbor-app>
    <script type="text/javascript" src="/static/inline.bundle.js"></script>
    <script type="text/javascript" src="/static/scripts.bundle.js">
    </script>
    <script type="text/javascript" src="/static/styles.bundle.js">
    </script>
    <script type="text/javascript" src="/static/vendor.bundle.js"></script>
    <script type="text/javascript" src="/static/main.bundle.js"></script>
</body>

</html>root@iZ2ze7tbgo9lk7jubiy6tcZ:~#

**Comment by lifubang** [comment]
@zhouhaibing089 @garfield009 @gitter-badger @alibaba-oss

**Comment by zhouhaibing089** [comment]
@lifubang how about:
```console
$ curl -X GET http://127.0.0.1:18001/v2/
$ curl -X GET https://docker/acmcoder.com/v2/
```

**Comment by lifubang** [comment]
root@iZ2ze7tbgo9lk7jubiy6tcZ:~# curl -X GET https://docker.acmcoder.com/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

curl -X GET http://127.0.0.1:18001/v2/
这个会导致连9000多个18001端口。

**Comment by zhouhaibing089** [comment]
@lifubang 从上面的你的curl结果来看, df-daemon设置的reverse proxy是起作用的.

另外, 9000多个connection, 肯定是不正常, 我之前阅读代码的时候有注意过这个问题:

https://github.com/alibaba/Dragonfly/pull/12/files#diff-4f359ed254c9eb6bd948cc8ff5de74f0R64

如果df-daemon识别的request host不是localhost, 它会reverse-proxy到自己(于是造成了死循环). 虽然我还不确定是不是就是这个原因.

你能把这个9000多个connection的具体连接情况贴一下吗? 我猜测可能是在做auth challenge时.

**Comment by lifubang** [comment]
@zhouhaibing089 
tcp        0      0 172.17.229.159:59722    172.17.229.159:18001    ESTABLISHED
tcp        0      0 172.17.229.159:54742    172.17.229.159:18001    ESTABLISHED
tcp        0      0 172.17.229.159:58610    172.17.229.159:18001    ESTABLISHED
tcp        0      0 172.17.229.159:57552    172.17.229.159:18001    ESTABLISHED
tcp        0      0 172.17.229.159:52144    172.17.229.159:18001    ESTABLISHED
tcp        0      0 172.17.229.159:53020    172.17.229.159:18001    ESTABLISHED
tcp        0      0 172.17.229.159:50430    172.17.229.159:18001    ESTABLISHED
tcp        0      0 172.17.229.159:59610    172.17.229.159:18001    ESTABLISHED
tcp        0      0 172.17.229.159:53258    172.17.229.159:18001    ESTABLISHED
tcp        0      0 172.17.229.159:53036    172.17.229.159:18001    ESTABLISHED
tcp        0      0 172.17.229.159:56564    172.17.229.159:18001    ESTABLISHED
[18001.txt](https://github.com/alibaba/Dragonfly/files/1558024/18001.txt)

**Comment by zhouhaibing089** [comment]
@lifubang how about:

```
# tcpdump -i <interface> -w /tmp/dump.pcap
```

and past me the content of `/tmp/dump.pcap`?

**Comment by lifubang** [comment]
@zhouhaibing089 已经发到您的gmail邮箱。

**Comment by zhouhaibing089** [comment]
@lifubang 收到, 可是我没看到destination也为172.17.229.159的记录, 抓包过程中你有运行`docker pull`吗, 或者你再抓一下lo?

**Comment by lifubang** [comment]
@zhouhaibing089 刚才是eth0，确实在lo下。已发。

**Comment by zhouhaibing089** [comment]
@lifubang 没收到...

**Comment by lifubang** [comment]
@zhouhaibing089 
[dump.pcap.tar.gz](https://github.com/alibaba/Dragonfly/files/1558058/dump.pcap.tar.gz)

**Comment by zhouhaibing089** [comment]
<img width="1440" alt="screen shot 2017-12-14 at 1 50 43 pm" src="https://user-images.githubusercontent.com/4516999/33977445-e011e786-e0d5-11e7-8570-51e0c1634356.png">

注意看`Host`和`X-Forwarded-For`Header, 所以可以确定的是你遇到的问题就是我前面提到的死循环.

你给docker配置的registry mirror是`http://127.0.0.1:18001`吗?

**Comment by lifubang** [comment]
嗯。还真是，谢谢了。我之前是dockerd --registry-mirror=http://dockerhost.acmcoder.com:18001，改成localhost确实可以pull了，这个应该增加到文档当中去。@zhouhaibing089
这个pull public的项目是可以的，但是没法pull需要密码的私有项目。有什么参数或方法吗？

**Comment by zhouhaibing089** [comment]
> 但是没法pull需要密码的私有项目

1. 首先我不太确定registry-mirror是否支持private image. 按照官方文档, `--registry-mirror`只适用于mirror官方的repo(index.docker.io?)
2. 由于df-daemon只是一个简单的reverse-proxy, 所以按照道理来讲, 在你的场景下, `docker login 127.0.0.1:18001`应该也是可以的.
3. 最后df-daemon只是在`/v2/<name>/blobs/sha256:<digest>`这个api上做了下手脚(先调用dfget把文件取下来, 再把取下来的文件返回给docker). 若是private image, dfget估计也需要特殊的配置.

你可以发个新的issue.

**Comment by lifubang** [comment]
Thx. 新发个。
