### ISSUE TITLE
nginx的这一段配置什么用途？

### ISSUE THREAD

**Issue by yanggongwang** [alibaba/Dragonfly#2]
server {
      listen              8001;
      location / {
          root /home/admin/supernode/repo;
      }
  }

上面这段配置什么用途？root路径该如何写？另外，能不能提供中文文档呢？谢谢

**Comment by garfield009** [comment]
1，客户端下载文件的时候，会触发超级节点从文件源同步待下载的文件（被动cdn方式），如果超级节点中已经保存有对应的文件，那么无需回源下载，直接使用缓存文件即可。
2，8001端口对应一个nginx文件服务器，通过8001端口，p2p客户端会从超级节点下载初始的分块数据，然后迅速传播给其他客户端。只有很小部分的客户端从超级节点下载。
3，root路径是一个目录：超级节点会把待下载的文件保存到该目录中；该路径目前是写死的，如果要改动，需要改这个配置文件和超级节点的源码
4，目前都是英文文档，如果有哪里不清楚，可以随时issue给我们。

**Comment by July-NetEase** [comment]
打扰一下！
由于我的客户端的数量很少（小于20台），部署时只有一个超级节点，且超级节点就是file server。
在配置时我想把root目录直接改成源文件所在的目录，除了修改nginx的配置，在超级节点的源码中还需改哪些地方？
谢谢！

**Comment by lowzj** [comment]
@July-NetEase 需要修改 [Constants.CDN_HOME](https://github.com/alibaba/Dragonfly/blob/master/src/supernode/src/main/java/com/alibaba/dragonfly/supernode/common/Constants.java#L30)
```java
public class Constants {
    ...
    public static final String CDN_HOME = "/home/admin/supernode/repo";
    ...
}
```
