### ISSUE TITLE
使用说明 看得不是很明白

### ISSUE THREAD

**Issue by jacky098123** [alibaba/Dragonfly#22]
https://github.com/alibaba/Dragonfly/blob/master/docs/usage.md

dfget 没有启动后台服务之类的，如何组成P2P

搞了一天，感觉有点懵

**Comment by jacky098123** [comment]
http://www.sohu.com/a/204573030_740477

config service 和 cluster manager 这两个，文档中都没有提及

**Comment by garfield009** [comment]
开源版本没有config server
