### ISSUE TITLE
使用经验（经过2天，终于work了）

### ISSUE THREAD

**Issue by jacky098123** [alibaba/Dragonfly#23]
从我使用的角度出发，碰到的问题，记录一下
* tomcat 要设置 UMASK，要不然，下的文件nginx是无法读取的，dfget 永远也拿不到
* tomcat 不知道什么原因，如果 supernode 第一次部署不正确，以后即使更新也还是老的，办法就是删除目录，重新解压tomcat
* tomcat server.xml 里的***_HOME 不work，人肉写成了绝对路径
* /etc/dragonfly.conf 是在 dfget 所在的 host上配置的，最开始以为是 supernode 的配置
* supernode 里面的目录信息，需要根据用户的情况进行修改
    src/main/java/com/alibaba/dragonfly/supernode/common/Constants.java
    src/main/resources/logback-config.properties
* 系统必须按照 淘宝最新的 tsar 软件包

**Comment by jacky098123** [comment]
就目前的开源状况，只是 CDN 的功能，没有看到如何搞 P2P
测试了一下下载，2.9G 的文件，性能只有scp 的 1/8 。。。

**Comment by garfield009** [comment]
1，蜻蜓有默认限速20MB，不知道你的机器网速如何
2，没有看到如何搞P2P是什么意思？
3，对超级节点的性能还是有一定要求的，尤其是网卡速率，毕竟初始的文件是由超级节点从源下载过来的；所以超级节点的网速太低也会影响整体下载速率，你可以第一次下载后，在进行第二次下载看看速率如何

**Comment by garfield009** [comment]
客户端的网速配置配置高些，然后看下同一个文件第二次下载的耗时如何

**Comment by foxwang** [comment]
@jacky098123  能提供下你的部署使用文档么，谢谢

**Comment by jacky098123** [comment]
@garfield009 
1. 现在服务器的网卡最少是千兆，很多是万兆。虽然没有确认是千兆还是万兆，但是同样的从远程拿一个文件，通过dragonfly 的效率是 scp 的 1/8。
另外，我试了一下 transmission daemon，效率也大约是 scp 的 1/8。但是 transmission 是真P2P
2. P2P 是每个client 都是一直运行着，这样其他client才能从他这里拿数据。但是 dfget 是只从 server 上请求，没有服务。不知道是不是我哪里配置有问题。
3. 在同一个客户端，无论下载多少次，耗时都差不多（scp 的 1/8）

**Comment by jacky098123** [comment]
@foxwang 我把所有遇到的坑都写出来了，其他的你dragonfly 的部署文档即可

**Comment by nonly** [comment]
@jacky098123  你试过源码编译安装server么，我install server遇到点问题。
