### ISSUE TITLE
Host(dfget节点)如何与CM组成P2P网络

### ISSUE THREAD

**Issue by foxwang** [alibaba/Dragonfly#25]
文档很简单，但部署完后万群不知道client节点如何与CM交互
dfget的测试，完全和wget没什么区别，理解上CM是作为源站的代理存在的，但完全不知道怎么配置
谢谢

**Comment by chenchaobing** [comment]
CM不仅仅是作为源站的代理，还会把从源下载的数据，提供分片下载。蜻蜓客户端从CM下载分片数据，然后会组成P2P网络。蜻蜓客户端目前是通过配置文件，来指定CM解决，也可以通过参数来指定。

**Comment by nonly** [comment]
@chenchaobing  p2p性能测试如何，我的环境dfget客户端比较少(<10个)，和wget对比感觉没有速度优势；

**Comment by chenchaobing** [comment]
@nonly  p2p是在同时下载的客户端节点数越多的情况下，p2p的效果会越明显。
因为蜻蜓客户端本身是会有限速的，再加上使用dfget下载的时候的时候，客户端会跟CM进行通信，所以单个dfget的下载速度对比wget没有速度优势是正常的，可以调整客户端限速以及进程数再进行测试。

另外P2P可以解决源的带宽不足，源被打爆的场景。如果能够打满源的带宽，那么你再用dfget和wget进行测试，就能测试出比较明显的效果了。

**Comment by jacky098123** [comment]
dfget 难道不是执行完就退出了么，没有后台服务如何做给其他dfget传输数据？

**Comment by jacky098123** [comment]
@chenchaobing 看文档，只有在docker的情况下，调用proxy，proxy 是个后台进程。这种情况下才能进行 P2P。不知道是我搭的环境有问题，还是我理解有问题

**Comment by chenchaobing** [comment]
@jacky098123  dfget 执行完了并不会马上退出，会提供后台服务给其他的dfget传输数据，只有当一定时间点，没有任何请求时，那么dfget会触发清理操作，把本地缓存的文件清理，同时真正退出进程。

**Comment by chenchaobing** [comment]
@jacky098123 docker的请求下，proxy只是为了把拉取镜像的请求代理到dfget，真正的p2p逻辑还是在CM集群和dfget之间。
