### ISSUE TITLE
安装server的问题

### ISSUE THREAD

**Issue by nonly** [alibaba/Dragonfly#26]
按照文档install_server.md安装；
按照docker方式部署，dockerfile里面的一些url已经失效，比如jdk等；
是否可以更新下install_server.md 以及dockerfile；

**Comment by chenchaobing** [comment]
恩，下周会更新一下。

**Comment by chenchaobing** [comment]
hi，多谢反馈，已经更新dockerfile的配置。

**Comment by nonly** [comment]
已验证，多谢
