### ISSUE TITLE
按文档使用docker build失败

### ISSUE THREAD

**Issue by tangramor** [alibaba/Dragonfly#28]
应该是镜像文件缺失了

Step 8/19 : RUN wget http://mirrors.hust.edu.cn/apache/tomcat/tomcat-7/v7.0.84/b
in/apache-tomcat-7.0.84.tar.gz -O /tmp/apache-tomcat-7.0.84.tar.gz     && cd /us
r/local && tar xzf /tmp/apache-tomcat-7.0.84.tar.gz     && ln -s /usr/local/apac
he-tomcat-7.0.84 /usr/local/tomcat     && rm /tmp/apache-tomcat-7.0.84.tar.gz
 ---> Running in c07a53d81f55
--2018-02-22 09:40:12--  http://mirrors.hust.edu.cn/apache/tomcat/tomcat-7/v7.0.
84/bin/apache-tomcat-7.0.84.tar.gz
Resolving mirrors.hust.edu.cn (mirrors.hust.edu.cn)... 202.114.18.160
Connecting to mirrors.hust.edu.cn (mirrors.hust.edu.cn)|202.114.18.160|:80... co
nnected.
HTTP request sent, awaiting response... 404 Not Found
2018-02-22 09:40:16 ERROR 404: Not Found.

The command '/bin/sh -c wget http://mirrors.hust.edu.cn/apache/tomcat/tomcat-7/v
7.0.84/bin/apache-tomcat-7.0.84.tar.gz -O /tmp/apache-tomcat-7.0.84.tar.gz     &
& cd /usr/local && tar xzf /tmp/apache-tomcat-7.0.84.tar.gz     && ln -s /usr/lo
cal/apache-tomcat-7.0.84 /usr/local/tomcat     && rm /tmp/apache-tomcat-7.0.84.t
ar.gz' returned a non-zero code: 8

**Comment by chenchaobing** [comment]
这是因为tomcat的下载地址发生变化导致的。需要替换tomcat的url。
