### ISSUE TITLE
关于客户端连接数的限制

### ISSUE THREAD

**Issue by joey71765** [alibaba/Dragonfly#30]
目前只提供了客户端带宽的限制功能，但是没有连接数的限制功能，会不会有可能导致连接数过高呢，还是说代码中有默认做了限制。我们比较关心连接数是否可控。

**Comment by chenchaobing** [comment]
目前没有参数来控制客户端的连接数。
现在保证连接数可控的最主要的一个手段是通过cluster Manager返回给蜻蜓客户端可下载的任务数来控制。对于一次下载请求,cluster Manager返回给客户端的任务数是可控的。

**Comment by joey71765** [comment]
请问具体是怎么控制呢，是代码写好限制还是可以通过调整参数？请问 默认一次下载请求的任务数是多少

**Comment by chenchaobing** [comment]
Cluster Manager中有个PEER_DOWN_LIMIT的限制，现在的限制是4.
