### ISSUE TITLE
It Pulling repository from docker.io

### ISSUE THREAD

**Issue by zhengweina** [alibaba/Dragonfly#31]
I configure as the guide . when I use docker pull , example docker pull test/alpine:latest，default， it Pulling repository docker.io/test/alpine .
How can I config docker?

**Comment by chenchaobing** [comment]
star df-daemon like this？
./df-daemon --registry http://harbor-noah.test.com

**Comment by zhengweina** [comment]
Yes, I have start df-daemon with my regstry.
like ./df-daemon --registry http://myharbor.test.com

I guess my docker has not load the configuration.
/etc/docker/daemon.json

[root@l-cmake logs]# ps -ef |grep df
root      55768  54782  0 Mar01 pts/0    00:00:01 df-daemon --registry http://dockerhub.test.com -port 65001

I start the docker with the command : service docker start

**Comment by chenchaobing** [comment]
could you show me the config of daemon.json？

**Comment by zhengweina** [comment]
[root@l-cmake docker]# cat daemon.json 
{
  "registry-mirrors": ["http://127.0.0.1:65001"]
}

**Comment by chenchaobing** [comment]
does it work use "docker pull harbor-noah.test.com/test/alpine:latest" ?
