### ISSUE TITLE
关于supervernode节点去源站下载的带宽限制

### ISSUE THREAD

**Issue by joey71765** [alibaba/Dragonfly#33]
目前dfget可以控制下载速度，那么supervernode节点去源站下载的时候请问这个带宽有没有办法控制呢。

**Comment by chenchaobing** [comment]
超级节点目前没有去控制超级节点可以从源下载的数量或者速度。

如果多个客户端节点从超级节点下载的是同一个文件，那么在超级节点上只会触发一个下载任务，即只会请求源一次。如果客户端节点都是下载的不同的文件，那么超级节点的网卡带宽以及源的带宽可能会成为瓶颈（多个客户端节点都是从同一个源下载不同的文件的情况）。

**Comment by joey71765** [comment]
感谢兵哥
