### ISSUE TITLE
dfget是否支持像wget那样的断点续传

### ISSUE THREAD

**Issue by joey71765** [alibaba/Dragonfly#34]
从客户端代码中没有找到相关的功能，请问是每次下载中断后，都需要重新下载整个文件吗

**Comment by chenchaobing** [comment]
蜻蜓的超级节点（cluster manager）从源下载文件，是支持断点续传的。

客户端从源下载资源，目前是采用分片下载的机制，即一个大文件会被分为很多的小分片下载。如果本地下载成功的分片没有被清理，那么是不需要重新下载整个文件的。

**Comment by joey71765** [comment]
谢谢兵哥～
