### ISSUE TITLE
蜻蜓有默认限速20MB，怎么改成无限制，求指导。

### ISSUE THREAD

**Issue by zhangzhenyu2** [alibaba/Dragonfly#38]
蜻蜓有默认限速20MB，怎么改成无限制，求指导。

**Comment by lowzj** [comment]
* 蜻蜓客户端默认下载限速10MB/s, 可以通过命令行选项`--locallimit`或`-s`调整单个任务的限速，另外选项`--totallimit`可用于限制单台机器上所有任务的总速度。
* 超级节点下载限速默认是180MB/s，可以通过http 请求超级节点`/super/config`来调整限速，参考[ConfigServlet](https://github.com/alibaba/Dragonfly/blob/master/src/supernode/src/main/java/com/alibaba/dragonfly/supernode/api/ConfigServlet.java#L41)。

目前代码中，两者都没办法改成无限制，只能调大限速。

**Comment by zhangzhenyu2** [comment]
@lowzj docker pull 的速度如何增加？--locallimit或-s是在dfget用的吧

**Comment by lowzj** [comment]
@zhangzhenyu2 `docker pull`的限速是由`df-daemon`控制的, 如: 启动`df-daemon`的时候加上选项`--ratelimit 20M`或者`--ratelimit 20480K`表示限速为20MB/s, 每一次`docker pull`时, `df-daemon`会调用`dfget`并将其`--locallimit`置为20M.

**Comment by zhangzhenyu2** [comment]
@lowzj 非常感谢
