### ISSUE TITLE
[question] 关于几点功能的疑问

### ISSUE THREAD

**Issue by joey71765** [alibaba/Dragonfly#49]
1，磁盘IO频率控制和磁盘空间检查，这个具体是怎么实现的，在客户端代码中的可控参数中并没有找到这类控制参数

2，全局和局部限速这个可以简单的说明一下区别吗

3，白名单功能具体指实现了什么样的功能
感谢

**Comment by nonly** [comment]
2，针对peer回答下，望补充；peer同时做client和server，total rate limit是指server的限速，local rate limit是对client下载而言，task级别的；

**Comment by lowzj** [comment]
@joey71765 目前内部版本有些功能还没有开放到开源版本中，1/3开源版中还没提供。
@joey71765 @nonly 针对第2点，全局限速(total rate limit)是针对单机(不是对server上传的限速)，局部限速(local rate limit)针对单任务。每个机器上可以启动多个`dfget`进程，每个`dfget`进程启动时，会检查本机器上的server端口是否占用，如果未占用则启动server，由server控制全局限速。

**Comment by nonly** [comment]
@lowzj 问下启动的dfget进程数量有限制么？这个是根据total rate limit进行限制么

**Comment by lowzj** [comment]
@nonly 没有限制，单机多dfget进程，会根据local rate limit计算比例，然后依此比例分配total rate limit，重新设置每个task的local rate limit。

**Comment by joey71765** [comment]
@lowzj @nonly 明白了，十分感谢
