### ISSUE TITLE
[question] 服务器客户端所用端口确认与NAT Traversal

### ISSUE THREAD

**Issue by junlicn** [alibaba/Dragonfly#55]
1. 服务器端用的端口是：80, 8001,8002 ? 还有么？

2. 客户端用什么端口？

3. 都是TCP协议么？

4. 如果我的客户端分布在互联网上，设置防火墙需要开放哪些端口？

5. 客户端如果是位于路由器防火墙后面，而且没有公网, 端口映射要做哪些？ 本身是否支持NAT Traversal?
不是 uPnP，PMP这种路由器性质的穿越。

6. 支持p2p传输的最大文件是多大？

**Comment by lowzj** [comment]
1. 服务端端口:  8001, 8002
2. 客户端上传服务的端口是浮动的，不固定
3. 使用的是http
4&5. 蜻蜓并不适合这种场景
6. 支持10GB级大文件10万级规模以上传输
