### ISSUE TITLE
[chore] Add docker build CI

### ISSUE THREAD

**Issue by wrfly** [alibaba/Dragonfly#58]
I could not build that image following the installation the docs provided. Some links were broken.
Maybe you can add some docker CI for it or just build the `dragonfly` and put it in alibaba's registry.
Thanks.

**Comment by lowzj** [comment]
Thanks for your suggestion! We are going to improve the project's CI flow and we also welcome your pull request if have you have time^-^.

**Comment by lowzj** [comment]
closed by #75
