### ISSUE TITLE
没有中文文档？阿里的开源还是国人支持的多吧，请不要搞得太高逼格，最起码中英双文档吧

### ISSUE THREAD

**Issue by soockie** [alibaba/Dragonfly#6]
sorry， i am looking for chinese document about this subject, but i can not find it , maybe somewhere i neglected.
so , as i know ,and i was an alibaba  R&D before,most of alibaba staff are chinese,i think it's easy to provide a zh-cn document, pls.

**Comment by lq08025107** [comment]
支持，拥抱国际化的同时宣扬民族文化

**Comment by garfield009** [comment]
ok，我们最近会补上中文文档，谢谢反馈。
