### ISSUE TITLE
[question] Is there any relationship between df-daemon and supernode?

### ISSUE THREAD

**Issue by wrfly** [alibaba/Dragonfly#64]
In the `Usage` part, I didn't see any configuration between df-daemon and supernode, but how can I download images from supernode?

In the architecture, when I pull images from df-daemon, df-daemon will try to connect the supernode(or the cluster manager, BTW, why give a different name?) and then supernode will connect to the docker registry.
But in practice, df-daemon will connect the registry directly(from logs and source code). Use the same port I specified in `docker pull`.

Steps:
- Start supernode `docker run --rm -ti -p 8001:8001 -p 8002:8002 dragonfly:supernode` but I don't know what's for.
- Start df-daemon: `./df-daemon -verbose -registry https://r.kfd.me` (BTW, why can't I use port lower than 2000? In https://github.com/alibaba/Dragonfly/blob/e42364eb8f1fb7a16295dcc5a4c3f2e7a5c6d468/src/daemon/src/df-daemon/initializer/initializer.go#L199)
- Pull some images: `docker pull r.kfd.me:65001/alpine` in another host which point r.kfd.me to the server.
- Got wrong.

Can you give a elaborate tutorial for setting up a docker-proxy? Or, it's a miss using that dragonfly can not be a docker proxy(just a mirror for now)?

**Comment by lowzj** [comment]
I'm very sorry about our unclear documents.

---

> the supernode(or the cluster manager, BTW, why give a different name?)

There is a part of this system named `cluster manage` in our internal version. But in open source version, we remove it and migrate some features of it to `supernode`. I think we should unify the name of `supernode` to avoid confusion.

---

The `df-daemon` and `supernode` are connected by the `dfget`. When you execute the following command:
```sh
docker pull centos:centos6
```
> NOTE: If you use _MIRROR_ pattern, you should remove the registry domain because that the domain was configured in `df-daemon` param `-registry`. If you are testing on MacOS, please set the `df-daemon` param `-hostIp` to a non-loop ip of your machine.

The complete flows are:
* `docker daemon` requests the `registry mirror(df-daemon)` to get every layers' url and downloads them
* `df-daemon` uses `dfget` to download every layers of image
* `dfget` connects to `supernode` to download the layer that `df-daemon` assigned, just like we use `dfget` to download files directly.
* `supernode` downloads the file(layer of image) from `registry`

---

`Df-daemon` now support _HTTP PROXY_ pattern but not support to pull a private image for now. We are improving documents recently and will add some content about _PROXY_ pattern.
