### ISSUE TITLE
enable CI for pull requests

### ISSUE THREAD

**Issue by zhouhaibing089** [alibaba/Dragonfly#7]
CI is very important to ensure PR satisfies some basic condition:

1. The code compiles.
2. UT is not broken.
3. etc

Is there a plan to add this?

**Comment by zhouhaibing089** [comment]
@garfield009 I am willing to help if you would like, IMHO, travis CI can be the first step.

**Comment by garfield009** [comment]
Alright, great！Have you tried to use dragonfly？

**Comment by zhouhaibing089** [comment]
@garfield009 we are evaluating many options as possible, I am looking into the code here this or two weeks, we will give it a try for sure later.

**Comment by garfield009** [comment]
ok, we have many internal features will be gradually opened.

**Comment by garfield009** [comment]
If you have any questions, please feel free to communicate

**Comment by zhouhaibing089** [comment]
@garfield009 if you don't mind, can we talk with email? (sadly I did not see the email in your profile).

**Comment by garfield009** [comment]
my email:1055471237@qq.com

**Comment by garfield009** [comment]
your prs have done.@zhouhaibing089

**Comment by zhouhaibing089** [comment]
@garfield009 actually I would like to keep this open until we have the proper ci integration for pull requests..

**Comment by garfield009** [comment]
yes,it is very important to add these ，it is very good if you can contribute it ^_^ 

发自我的 iPhone

**Comment by garfield009** [comment]
can we use Chinese to communicate?
 

发自我的 iPhone

**Comment by zhouhaibing089** [comment]
https://travis-ci.org/getting_started 需要repo的管理员权限才可以设置.

1. 用github账户注册travis-ci.org.
2. 选择需要集成的repo.
3. push一个配置文件.travis.yml.
