### ISSUE TITLE
[question] what is the p2p protocol used in Dragonfly, bittorrent?

### ISSUE THREAD

**Issue by caidongqing** [alibaba/Dragonfly#76]

**Comment by nonly** [comment]
https://github.com/alibaba/Dragonfly/blob/master/docs/en/api.md

**Comment by caidongqing** [comment]
蜻蜓应该是实现了一种类bittorrent的协议，supernode即为traker, 元信息文件 .meta 类似于.torrent文件，不知道这样理解对不对

**Comment by nonly** [comment]
我觉得是的

**Comment by lowzj** [comment]
理解正确，蜻蜓实现一个简单的p2p模式的自定义协议，其他可以参考: [comment](https://github.com/alibaba/Dragonfly/issues/50#issuecomment-382286474)
