### ISSUE TITLE
windows客戶端支持？

### ISSUE THREAD

**Issue by cxlRay** [alibaba/Dragonfly#9]
请问dfget支持windows平台吗？客户端有特别依赖linux特性的逻辑吗？谢谢

**Comment by cxlRay** [comment]
- 操作系统：windows 10
- Python版本：2.7.14
- Go版本：1.9
windows下编译出df-daemon.exe，测试了下http和https文件下载都没问题，python2.7.3测试时https下载报错，升级到2.7.14就解决了

**Comment by garfield009** [comment]
目前只依赖fork 系统调用
兼容下这个就可以在windows 上使用

发自我的 iPhone

**Comment by cxlRay** [comment]
客户端fork调用这块代码看了几遍不是特别明白，可以把核心逻辑解释一下吗，我们准备尝试修改兼容windows

**Comment by garfield009** [comment]
第一次fork是把下载进程和服务进程分叉，后续的fork是把服务进程置为daemon模式，windows兼容可以考虑用multiprocessing这个库

**Comment by cxlRay** [comment]
好的，我们尝试下，谢谢
