### ISSUE TITLE
[question] dragonfly 主机级别限速问题

### ISSUE THREAD

**Issue by U201114227** [alibaba/Dragonfly#95]
您好，我是华中科技大学的一名研究生，我在github上看到了阿里巴巴开源的文件分发系统的源码draonfly，该系统中提到提供主机级别限速的功能，我对这方面很感兴趣，在阅读源码的过程中，有一些地方不太理解，源码的gettet模块是客户端处理文件分发和共享的模块，其中有一个componnet中有一个ratelimiter的类是用来限速的，其中有几个关键变量token和window是具体代表什么呢？没有特别弄明白。
    另外，我想问一下您的主机限速的逻辑是什么呢？是怎么保证该主机的速度不超过其设置的运行速度的呢？

**Comment by lowzj** [comment]
> `token`与`window`代表什么?

dfget里实现里一个简单的令牌桶算法(token-bucket)来限流，关于限流的一些文章可以参考[这里](https://lowzj.com/notes/microservices/share.html#api%E9%99%90%E6%B5%81)。

关于令牌桶算法，下面节选自[Wikipedia](https://en.wikipedia.org/wiki/Token_bucket):
```
The token bucket algorithm can be conceptually understood as follows:

1. A token is added to the bucket every {\displaystyle 1/r} 1/r seconds.
2. The bucket can hold at the most {\displaystyle b} b tokens. If a token arrives when the bucket is full, it is discarded.
3. When a packet (network layer PDU) of n bytes arrives, n tokens are removed from the bucket, and the packet is sent to the network.
4. If fewer than n tokens are available, no tokens are removed from the bucket, and the packet is considered to be non-conformant.
```

代码里的`token`跟这里的`token`完全一致。`window`类似于维基里说的`1/r seconds`，表示产生令牌的间隔，`window`期间产生的令牌数由`rate`指定。

---

> 主机限速的逻辑

同一台机器上，第一个dfget进程启动时，会同时启动一个`server`进程用来做p2p里的上传服务，端口会保存在本地的meta文件里；当其他dfget启动时，会检查是否有`server`已经启动了，有的话，上报自己的限速参数，由`server`计算出各个dfget任务的速率比例，再按此比例重新分配totallimit值，各个dfget任务按此新值来限速。
